/random/setSeeds 12345 67890
/sim/particle proton
/sim/sensitiveXY 10 um
/sim/deadXY 10 um
/sim/sensitiveThickness 8 um
/sim/deadThickness 5 um
/sim/biasCrossSectionFactor 1041
/sim/useCollectionModel true
/sim/carrierLifetime 1.0 ns
/sim/electricField 1000000 volt/m
/run/initialize
/run/reinitializeGeometry

/sim/energy 200 MeV
/sim/beamXY 10 um
/sim/criticalCharge 150
/sim/verbose false
/run/beamOn 10000000
