/random/setSeeds 55533 55544
/sim/particle alpha
/sim/energy 200 MeV
/sim/sensitiveXY 10 um
/sim/deadXY 10 um
/sim/sensitiveThickness 8 um
/sim/deadThickness 5 um
/sim/beamXY 10 um
/sim/criticalCharge 150
/sim/useCollectionModel true

/sim/biasCrossSectionFactor 1

/sim/carrierLifetime 1.0 ns
/sim/electricField 1000000 volt/m
/sim/verbose false

/run/initialize
/run/reinitializeGeometry

/run/beamOn 10000000
